from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from game.utils import clickable

try:
    _fromUtf8 = lambda s: s
except AttributeError:
    def _fromUtf8(s):
        return s

class Leader_icon(QWidget):
    '''
    Either Captain or Hierophant  widget
    '''
    def __init__(self, parent=None):
        super(QWidget,self).__init__(parent)
        self.gridLayoutWidget = QWidget()
        self.gridLayoutWidget.setGeometry(QRect(80, 342, 181, 119))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(3, -1, 3, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.exp_bar = QProgressBar(self.gridLayoutWidget)
        self.exp_bar.setMaximumSize(QSize(120, 4))
        self.exp_bar.setStyleSheet("::chunk {background-color:purple }")
        self.exp_bar.setTextVisible(False)
        self.exp_bar.setOrientation(Qt.Horizontal)
        self.exp_bar.setObjectName(_fromUtf8("exp_bar"))
        self.gridLayout.addWidget(self.exp_bar, 2, 0, 1, 1)
        self.titleBar = QWidget(self.gridLayoutWidget)
        self.titleBar.setMinimumSize(QSize(180, 25))
        self.titleBar.setMaximumSize(QSize(125, 20))
        self.titleBar.setStyleSheet(_fromUtf8("background-color: lightgrey"))
        self.titleBar.setObjectName(_fromUtf8("titleBar"))
        self.vlLayout = QHBoxLayout(self.titleBar)
        self.vlLayout.setContentsMargins(-1, -1, -1, 4)
        self.vlLayout.setSpacing(3)
        self.vlLayout.setObjectName(_fromUtf8("vlLayout"))
        self.Unit_name = QLabel(self.titleBar)
        self.Unit_name.setMinimumSize(QSize(50, 15))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Unit_name.setFont(font)
        self.Unit_name.setStyleSheet(_fromUtf8(""))
        self.Unit_name.setObjectName(_fromUtf8("Unit_name"))
        self.vlLayout.addWidget(self.Unit_name)
        self.in_battle_squad_chbx = QCheckBox(self.titleBar)
        self.in_battle_squad_chbx.setMinimumSize(QSize(18, 16))
        self.in_battle_squad_chbx.setMaximumSize(QSize(18, 16))
        self.in_battle_squad_chbx.setObjectName(_fromUtf8("in_battle_squad_chbx"))
        self.vlLayout.addWidget(self.in_battle_squad_chbx)
        self.remove_unit = QPushButton(self.titleBar)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_unit.sizePolicy().hasHeightForWidth())
        self.remove_unit.setSizePolicy(sizePolicy)
        self.remove_unit.setMinimumSize(QSize(16, 16))
        self.remove_unit.setMaximumSize(QSize(16, 16))
        self.remove_unit.setObjectName(_fromUtf8("remove_unit"))
        self.vlLayout.addWidget(self.remove_unit)
        self.gridLayout.addWidget(self.titleBar, 0, 0, 1, 1)
        self.health_bar = QProgressBar(self.gridLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.health_bar.sizePolicy().hasHeightForWidth())
        self.health_bar.setSizePolicy(sizePolicy)
        self.health_bar.setMinimumSize(QSize(80, 4))
        self.health_bar.setMaximumSize(QSize(120, 4))
        self.health_bar.setStyleSheet("::chunk {background-color: red}")
        self.health_bar.setTextVisible(False)
        self.health_bar.setOrientation(Qt.Horizontal)
        self.health_bar.setObjectName(_fromUtf8("health_bar"))
        self.gridLayout.addWidget(self.health_bar, 1, 0, 1, 1)
        spacerItem1 = QSpacerItem(40, 20,
                                        QSizePolicy.Expanding,
                                        QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableWidget = QTableWidget(self.gridLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QSize(122, 50))
        self.tableWidget.setMaximumSize(QSize(125, 60))
        self.tableWidget.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(61)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(16)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(16)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QAbstractItemView.NoSelection)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        spacerItem2 = QSpacerItem(40, 20,
                                        QSizePolicy.Expanding,
                                        QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.level_up_button = QPushButton(self.gridLayoutWidget)
        self.level_up_button.setMinimumSize(QSize(25, 25))
        self.level_up_button.setMaximumSize(QSize(25, 25))
        self.level_up_button.setStyleSheet("background-color: green;"
                                           "color: black")
        self.level_up_button.setObjectName(_fromUtf8("level_up_button"))
        self.verticalLayout.addWidget(self.level_up_button)
        self.tree_button = QPushButton(self.gridLayoutWidget)
        self.tree_button.setMinimumSize(QSize(25, 25))
        self.tree_button.setMaximumSize(QSize(25, 25))
        self.tree_button.setStyleSheet(_fromUtf8("background-color: yellow;"
                                                 "color: black;"))
        self.tree_button.setObjectName(_fromUtf8("tree_button"))
        self.verticalLayout.addWidget(self.tree_button)
        spacerItem3 = QSpacerItem(20, 40,
                                        QSizePolicy.Minimum,
                                        QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QSpacerItem(40, 20,
                                        QSizePolicy.Expanding,
                                        QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.gridLayoutWidget.raise_()
        self.Unit_name.raise_()
        self.setLayout(self.gridLayout)

    def retranslate_widget(self, leader, expand, value=None):
        '''
        Fill widget with leader's data

        leader: units.Leader() object
        expand: function called when widget is clicked
        value: function argument
        '''
        item = self.tableWidget.item(0, 0)
        item.setText("MO: %s" % leader.morale)
        item = self.tableWidget.item(0, 1)
        item.setText(u"\xA3%s" % leader.cost)
        item = self.tableWidget.item(1, 0)
        item.setText("MV: %s" % leader.move)
        item = self.tableWidget.item(1, 1)
        item.setText("AR: %s" % leader.armour)
        item = self.tableWidget.item(2, 0)
        item.setText("SH: %s" % leader.shoot)
        item = self.tableWidget.item(2, 1)
        item.setText("FT: %s" % leader.fight)
        self.health_bar.setProperty("value", leader.health)
        self.exp_bar.setProperty("value", leader.experience)
        self.Unit_name.setText("%s" % leader.name)
        self.remove_unit.setText("x")
        self.level_up_button.setText("+")
        self.tree_button.setText("T")
        clickable(self).connect(lambda: expand(leader))
        self.tableWidget.itemClicked.connect(lambda: expand(leader))
