from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from game.utils import centre_window

try:
    _fromUtf8 = lambda s: s
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    '''
    Main window widget. Include main menu and RHS content areas

    Areas for widgets:
        self.solders_roster: soldiers grid in roster view
        self.solder_bt: as above but in battle team view
        self.active_layout: currently active layout (battle_team or roster)
        self.leaders_roster
        self.leaders_bt: area for leaders widgets
        self.unit_expanded_roster
        self.unit_expaned_bt: Table where unit skills are shown
                              in the exanded view
        self.unit_pic_roster
        self.unit_pic_bt: are for unit image
        self.unit_items_roster
        self.unit_items_bt: expanded view of unit items
    '''
    def setupUi(self, MainWindow, update_func):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 680)
        MainWindow.setStyleSheet(_fromUtf8("border-width: 5px;"))
        self.MainWindow = MainWindow
        self.update_content = update_func # comes from main.py
        self.centralwidget = QStackedWidget(self.MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 191, 663))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.main_menu_layout = QVBoxLayout(self.verticalLayoutWidget)
        self.main_menu_layout.setObjectName(_fromUtf8("main_menu_layout"))
        self.hr_line = QFrame(self.verticalLayoutWidget)
        self.hr_line.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line.setFrameShape(QFrame.HLine)
        self.hr_line.setFrameShadow(QFrame.Plain)
        self.hr_line.setLineWidth(3)
        self.hr_line.setObjectName(_fromUtf8("hr_line"))
        self.main_menu_layout.addWidget(self.hr_line)
        self.game_title_label = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.game_title_label.setFont(font)
        self.game_title_label.setAlignment(Qt.AlignCenter)
        self.game_title_label.setObjectName(_fromUtf8("game_title_label"))
        self.main_menu_layout.addWidget(self.game_title_label)
        self.hr_line_2 = QFrame(self.verticalLayoutWidget)
        self.hr_line_2.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line_2.setFrameShape(QFrame.HLine)
        self.hr_line_2.setFrameShadow(QFrame.Plain)
        self.hr_line_2.setLineWidth(3)
        self.hr_line_2.setObjectName(_fromUtf8("hr_line_2"))
        self.main_menu_layout.addWidget(self.hr_line_2)
        self.username_label = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.username_label.setFont(font)
        self.username_label.setAlignment(Qt.AlignCenter)
        self.username_label.setObjectName(_fromUtf8("username_label"))
        self.main_menu_layout.addWidget(self.username_label)
        spacerItem = QSpacerItem(20, 40,
                                       QSizePolicy.Minimum,
                                       QSizePolicy.Expanding)
        self.main_menu_layout.addItem(spacerItem)
        self.hr_line_3 = QFrame(self.verticalLayoutWidget)
        self.hr_line_3.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line_3.setFrameShape(QFrame.HLine)
        self.hr_line_3.setFrameShadow(QFrame.Plain)
        self.hr_line_3.setLineWidth(3)
        self.hr_line_3.setObjectName(_fromUtf8("hr_line_3"))
        self.main_menu_layout.addWidget(self.hr_line_3)
        self.squad_number_label = QLabel(self.verticalLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred,
                                       QSizePolicy.Preferred)
        self.squad_number_label.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.squad_number_label.setFont(font)
        self.squad_number_label.setAutoFillBackground(False)
        self.squad_number_label.setAlignment(Qt.AlignCenter)
        self.squad_number_label.setObjectName(_fromUtf8("squad_number_label"))
        self.main_menu_layout.addWidget(self.squad_number_label)
        self.hr_line_4 = QFrame(self.verticalLayoutWidget)
        self.hr_line_4.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line_4.setFrameShape(QFrame.HLine)
        self.hr_line_4.setFrameShadow(QFrame.Plain)
        self.hr_line_4.setLineWidth(3)
        self.hr_line_4.setObjectName(_fromUtf8("hr_line_4"))
        self.main_menu_layout.addWidget(self.hr_line_4)
        self.roster_button = QPushButton(self.verticalLayoutWidget)
        self.roster_button.setMinimumSize(QSize(30, 45))
        self.roster_button.setAutoDefault(False)
        self.roster_button.setDefault(False)
        self.roster_button.setFlat(False)
        self.roster_button.setObjectName(_fromUtf8("roster_button"))
        self.main_menu_layout.addWidget(self.roster_button)
        self.stash_button = QPushButton(self.verticalLayoutWidget)
        self.stash_button.setMinimumSize(QSize(0, 45))
        self.stash_button.setStyleSheet(_fromUtf8(""))
        self.stash_button.setObjectName(_fromUtf8("stash_button"))
        self.main_menu_layout.addWidget(self.stash_button)
        self.battle_team_button = QPushButton(self.verticalLayoutWidget)
        self.battle_team_button.setMinimumSize(QSize(0, 45))
        self.battle_team_button.setObjectName(_fromUtf8("battle_team_button"))
        self.main_menu_layout.addWidget(self.battle_team_button)
        spacerItem1 = QSpacerItem(20, 40,
                                        QSizePolicy.Minimum,
                                        QSizePolicy.Expanding)
        self.main_menu_layout.addItem(spacerItem1)
        self.hr_line_5 = QFrame(self.verticalLayoutWidget)
        self.hr_line_5.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line_5.setFrameShape(QFrame.HLine)
        self.hr_line_5.setFrameShadow(QFrame.Plain)
        self.hr_line_5.setLineWidth(3)
        self.hr_line_5.setObjectName(_fromUtf8("hr_line_5"))
        self.main_menu_layout.addWidget(self.hr_line_5)
        self.create_squad_grid = QHBoxLayout()
        self.create_squad_grid.setContentsMargins(20, -1, -1, -1)
        self.create_squad_grid.setObjectName(_fromUtf8("create_squad_grid"))
        self.create_new_squad_button = QPushButton(self.verticalLayoutWidget)
        self.create_new_squad_button.setMaximumSize(QSize(30, 30))
        self.create_new_squad_button.setStyleSheet(_fromUtf8("color: green;"))
        self.create_new_squad_button.setObjectName(_fromUtf8("create_new_squad_button"))
        self.create_squad_grid.addWidget(self.create_new_squad_button)
        self.create_new_squad_label = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        self.create_new_squad_label.setFont(font)
        self.create_new_squad_label.setObjectName(_fromUtf8("create_new_squad_label"))
        self.create_squad_grid.addWidget(self.create_new_squad_label)
        spacerItem2 = QSpacerItem(40, 20,
                                        QSizePolicy.Expanding,
                                        QSizePolicy.Minimum)
        self.create_squad_grid.addItem(spacerItem2)
        self.main_menu_layout.addLayout(self.create_squad_grid)
        self.delete_squad_grid = QHBoxLayout()
        self.delete_squad_grid.setContentsMargins(20, -1, -1, -1)
        self.delete_squad_grid.setObjectName(_fromUtf8("delete_squad_grid"))
        self.delete_squad_button = QPushButton(self.verticalLayoutWidget)
        self.delete_squad_button.setMaximumSize(QSize(30, 30))
        self.delete_squad_button.setStyleSheet(_fromUtf8("color: red;"))
        self.delete_squad_button.setObjectName(_fromUtf8("delete_squad_button"))
        self.delete_squad_grid.addWidget(self.delete_squad_button)
        self.delete_squad_label = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        self.delete_squad_label.setFont(font)
        self.delete_squad_label.setObjectName(_fromUtf8("delete_squad_label"))
        self.delete_squad_grid.addWidget(self.delete_squad_label)
        spacerItem3 = QSpacerItem(40, 20,
                                        QSizePolicy.Expanding,
                                        QSizePolicy.Minimum)
        self.delete_squad_grid.addItem(spacerItem3)
        self.main_menu_layout.addLayout(self.delete_squad_grid)
        self.hr_line_6 = QFrame(self.verticalLayoutWidget)
        self.hr_line_6.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line_6.setFrameShape(QFrame.HLine)
        self.hr_line_6.setFrameShadow(QFrame.Plain)
        self.hr_line_6.setLineWidth(3)
        self.hr_line_6.setObjectName(_fromUtf8("hr_line_6"))
        self.main_menu_layout.addWidget(self.hr_line_6)
        spacerItem4 = QSpacerItem(20, 40,
                                        QSizePolicy.Minimum,
                                        QSizePolicy.Expanding)
        self.main_menu_layout.addItem(spacerItem4)
        self.unit_recruitment_button = QPushButton(self.verticalLayoutWidget)
        self.unit_recruitment_button.setMinimumSize(QSize(0, 45))
        self.unit_recruitment_button.setObjectName(_fromUtf8("unit_recruitment_button"))
        self.main_menu_layout.addWidget(self.unit_recruitment_button)
        self.buy_equipment_button = QPushButton(self.verticalLayoutWidget)
        self.buy_equipment_button.setMinimumSize(QSize(0, 45))
        self.buy_equipment_button.setStyleSheet(_fromUtf8(""))
        self.buy_equipment_button.setObjectName(_fromUtf8("buy_equipment_button"))
        self.main_menu_layout.addWidget(self.buy_equipment_button)
        self.hr_line_7 = QFrame(self.verticalLayoutWidget)
        self.hr_line_7.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line_7.setFrameShape(QFrame.HLine)
        self.hr_line_7.setFrameShadow(QFrame.Plain)
        self.hr_line_7.setLineWidth(3)
        self.hr_line_7.setObjectName(_fromUtf8("hr_line_7"))
        self.main_menu_layout.addWidget(self.hr_line_7)
        self.players_online_button = QPushButton(self.verticalLayoutWidget)
        self.players_online_button.setMinimumSize(QSize(0, 45))
        self.players_online_button.setObjectName(_fromUtf8("players_online_button"))
        self.main_menu_layout.addWidget(self.players_online_button)
        self.hr_line_8 = QFrame(self.verticalLayoutWidget)
        self.hr_line_8.setStyleSheet(_fromUtf8("color: black;"))
        self.hr_line_8.setFrameShape(QFrame.HLine)
        self.hr_line_8.setFrameShadow(QFrame.Plain)
        self.hr_line_8.setLineWidth(3)
        self.hr_line_8.setObjectName(_fromUtf8("hr_line_8"))
        self.main_menu_layout.addWidget(self.hr_line_8)
        self.exit_button = QPushButton(self.verticalLayoutWidget)
        self.exit_button.setMinimumSize(QSize(0, 45))
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.exit_button.clicked.connect(QCoreApplication.instance().quit)
        self.main_menu_layout.addWidget(self.exit_button)
        self.roster_button.raise_()
        self.stash_button.raise_()
        self.battle_team_button.raise_()
        self.game_title_label.raise_()
        self.username_label.raise_()
        self.exit_button.raise_()
        self.players_online_button.raise_()
        self.buy_equipment_button.raise_()
        self.unit_recruitment_button.raise_()
        self.squad_number_label.raise_()
        self.hr_line.raise_()
        self.hr_line_2.raise_()
        self.hr_line_3.raise_()
        self.hr_line_4.raise_()
        self.hr_line_6.raise_()
        self.hr_line_7.raise_()
        self.hr_line_8.raise_()
        self.hr_line_5.raise_()
		# battle button
        self.battle_button = QPushButton(self.centralwidget)
        self.battle_button.setGeometry(QRect(870, 570, 141, 71))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battle_button.setFont(font)
        self.battle_button.setObjectName(_fromUtf8("battle_button"))
		# matching box
        self.matching_chbox = QCheckBox(self.centralwidget)
        self.matching_chbox.setGeometry(QRect(860, 650, 151, 22))
        self.matching_chbox.setObjectName(_fromUtf8("matching_chbox"))
		# unit notes
        self.unit_notes2 = QTextBrowser(self.centralwidget)
        self.unit_notes2.setGeometry(QRect(540, 570, 301, 101))
        self.unit_notes2.setObjectName(_fromUtf8("unit_notes2"))
        self.unit_notes1 = QTextBrowser(self.centralwidget)
        self.unit_notes1.setGeometry(QRect(220, 570, 301, 101))
        self.unit_notes1.setObjectName(_fromUtf8("unit_notes1"))
		# top right corner
        self.verticalLayoutWidget_4 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QRect(840, 10, 171, 101))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.top_right = QVBoxLayout(self.verticalLayoutWidget_4)
        self.top_right.setObjectName(_fromUtf8("top_right"))
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.available_for_battle_label = QLabel(self.verticalLayoutWidget_4)
        font = QFont()
        font.setPointSize(10)
        self.available_for_battle_label.setFont(font)
        self.available_for_battle_label.setAlignment(Qt.AlignCenter)
        self.available_for_battle_label.setObjectName(_fromUtf8("available_for_battle_label"))
        self.horizontalLayout_3.addWidget(self.available_for_battle_label)
        self.available_for_battle_slider = QSlider(self.verticalLayoutWidget_4)
        self.available_for_battle_slider.setMaximumSize(QSize(50, 16777215))
        self.available_for_battle_slider.setLayoutDirection(Qt.LeftToRight)
        self.available_for_battle_slider.setInputMethodHints(Qt.ImhNone)
        self.available_for_battle_slider.setMaximum(1)
        self.available_for_battle_slider.setOrientation(Qt.Horizontal)
        self.available_for_battle_slider.setInvertedControls(False)
        self.available_for_battle_slider.setObjectName(_fromUtf8("available_for_battle_slider"))
        self.horizontalLayout_3.addWidget(self.available_for_battle_slider)
        self.top_right.addLayout(self.horizontalLayout_3)
        self.credits_label = QLabel(self.verticalLayoutWidget_4)
        self.credits_label.setMinimumSize(QSize(0, 25))
        font = QFont()
        font.setPointSize(15)
        self.credits_label.setFont(font)
        self.credits_label.setAlignment(Qt.AlignCenter)
        self.credits_label.setObjectName(_fromUtf8("credits_label"))
        self.top_right.addWidget(self.credits_label)
		# messaging area
        self.verticalLayoutWidget_3 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QRect(210, 10, 621, 101))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.messaging_area = QTextEdit(self.verticalLayoutWidget_3)
        self.messaging_area.setObjectName(_fromUtf8("messaging_area"))
        self.messaging_area.setReadOnly(True)
        self.messaging_area.setMinimumSize(621,101)
        self.messaging_area.setMaximumSize(621,101)
        self.messaging_area.insertPlainText('Welcome To The Game II\n')
        self.generate_roster_layout()
        self.roster.raise_()
        self.active_layout = self.roster
        self.roster.show()
        self.roster_button.clicked.connect(lambda: self.show_layout(self.roster))
        self.generate_battle_team_layout()
        self.battle_team.raise_()
        self.battle_team.hide()
        self.battle_team_button.clicked.connect(lambda: self.show_layout(self.battle_team))
        self.battle_button.raise_()
        self.matching_chbox.raise_()
        self.unit_notes2.raise_()
        self.unit_notes1.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.verticalLayoutWidget_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        #QMetaObject.connectSlotsByName(self.centralwidget)
        centre_window(MainWindow)

    def show_layout(self, layout):
        '''
        Show requested layout, hide old one
        '''
        self.active_layout.hide()
        self.active_layout = layout
        self.update_content()
        layout.show()

    def generate_roster_layout(self):
        '''
        Generate layout for the Roster Tab
        '''
        self.roster = QWidget(self.centralwidget)
        self.roster.setGeometry(QRect(210, 120, 801, 441))
        self.roster.setObjectName(_fromUtf8("roster"))
        # Soldiers Grid
        self.gridLayoutWidget = QWidget(self.roster)
        self.gridLayoutWidget.setGeometry(QRect(390, 150, 431, 290))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.scrollArea = QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setMinimumSize(410, 290)
        self.scrollArea.setMaximumSize(410, 290)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.soldiers_roster = QGridLayout(self.scrollAreaWidgetContents_2)
        self.soldiers_roster.setContentsMargins(1, 1, 15, 10)
        self.soldiers_roster.setObjectName(_fromUtf8("soldiers_roster"))
        self.soldiers_roster.setAlignment(Qt.AlignLeft|Qt.AlignTop)
        # End of Soldiers Grid
        self.gridLayoutWidget_2 = QWidget(self.roster)
        self.gridLayoutWidget_2.setGeometry(QRect(390, 10, 431, 131))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))

        self.leaders_roster = QGridLayout(self.gridLayoutWidget_2)
        self.leaders_roster.setObjectName(_fromUtf8("leaders_roster"))
        self.unit_pic_roster = QWidget(self.roster)
        self.unit_pic_roster.setGeometry(QRect(180, 10, 181, 181))
        self.gridLayoutWidget_3 = QWidget(self.roster)
        self.gridLayoutWidget_3.setGeometry(QRect(187, 200, 181, 231))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.unit_items_roster = QGridLayout(self.gridLayoutWidget_3)
        self.unit_items_roster.setObjectName(_fromUtf8("unit_items_roster"))
        self.verticalLayoutWidget_2 = QWidget(self.roster)
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 10, 171, 421))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.unit_expanded_roster = QVBoxLayout(self.verticalLayoutWidget_2)
        self.unit_expanded_roster.setObjectName(_fromUtf8("unit_expanded_roster"))


    def generate_battle_team_layout(self):
        self.battle_team = QWidget(self.centralwidget)
        self.battle_team.setGeometry(QRect(210, 120, 801, 441))
        self.battle_team.setObjectName(_fromUtf8("battle_team"))
        # Soldiers grid
        self.gridLayoutWidget = QWidget(self.battle_team)
        self.gridLayoutWidget.setGeometry(QRect(390, 150, 431, 290))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.scrollArea = QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setMinimumSize(410, 290)
        self.scrollArea.setMaximumSize(410, 290)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.soldiers_bt = QGridLayout(self.scrollAreaWidgetContents_2)
        self.soldiers_bt.setContentsMargins(1, 1, 15, 10)
        self.soldiers_bt.setObjectName(_fromUtf8("soldiers_bt"))
        self.soldiers_bt.setAlignment(Qt.AlignLeft|Qt.AlignTop)
        # End of Soldiers grid
        self.gridLayoutWidget_2 = QWidget(self.battle_team)
        self.gridLayoutWidget_2.setGeometry(QRect(390, 10, 431, 131))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.leaders_bt = QGridLayout(self.gridLayoutWidget_2)
        self.leaders_bt.setObjectName(_fromUtf8("leaders_bt"))
        self.unit_pic_bt = QWidget(self.battle_team)
        self.unit_pic_bt.setGeometry(QRect(180, 10, 181, 181))
        self.gridLayoutWidget_4 = QWidget(self.battle_team)
        self.gridLayoutWidget_4.setGeometry(QRect(187, 200, 181, 231))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.unit_items_bt = QGridLayout(self.gridLayoutWidget_4)
        self.unit_items_bt.setObjectName(_fromUtf8("unit_items_bt"))
        self.verticalLayoutWidget_2 = QWidget(self.battle_team)
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 10, 171, 421))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.unit_expanded_bt = QVBoxLayout(self.verticalLayoutWidget_2)
        self.unit_expanded_bt.setObjectName(_fromUtf8("unit_expanded_bt"))

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.game_title_label.setText(_translate("MainWindow", "The Game II", None))
        self.username_label.setText(_translate("MainWindow", "username", None))
        self.squad_number_label.setText(_translate("MainWindow", "Squad", None))
        self.roster_button.setText(_translate("MainWindow", "Roster", None))
        self.stash_button.setText(_translate("MainWindow", "Stash", None))
        self.battle_team_button.setText(_translate("MainWindow", "Battle Team", None))
        self.create_new_squad_button.setText(_translate("MainWindow", "+", None))
        self.create_new_squad_label.setText(_translate("MainWindow", "Create New Squad", None))
        self.delete_squad_button.setText(_translate("MainWindow", "x", None))
        self.delete_squad_label.setText(_translate("MainWindow", "Delete Squad", None))
        self.unit_recruitment_button.setText(_translate("MainWindow", "Unit Recruitment", None))
        self.buy_equipment_button.setText(_translate("MainWindow", "Buy Equipment", None))
        self.players_online_button.setText(_translate("MainWindow", "Players Online", None))
        self.exit_button.setText(_translate("MainWindow", "Exit", None))
        self.battle_button.setText(_translate("MainWindow", "Battle!", None))
        self.matching_chbox.setText(_translate("MainWindow", "Matching System", None))
        self.available_for_battle_label.setText(_translate("MainWindow", "Available for Battle", None))
        self.credits_label.setText(_translate("MainWindow", "Credits: $500", None))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
